try:
    func(None, "None")
except Exception:
    print("Ура! Ошибка!")